/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormCodeRouteImport } from './routes/form.$code'
import { Route as CaseSlugRouteImport } from './routes/case.$slug'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiCronSyncRouteImport } from './routes/api/cron/sync'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormCodeRoute = FormCodeRouteImport.update({
  id: '/form/$code',
  path: '/form/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSlugRoute = CaseSlugRouteImport.update({
  id: '/case/$slug',
  path: '/case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncRoute = ApiCronSyncRouteImport.update({
  id: '/api/cron/sync',
  path: '/api/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forms': typeof FormsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/track': typeof ApiTrackRoute
  '/case/$slug': typeof CaseSlugRoute
  '/form/$code': typeof FormCodeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forms': typeof FormsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/track': typeof ApiTrackRoute
  '/case/$slug': typeof CaseSlugRoute
  '/form/$code': typeof FormCodeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forms': typeof FormsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/track': typeof ApiTrackRoute
  '/case/$slug': typeof CaseSlugRoute
  '/form/$code': typeof FormCodeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forms'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/track'
    | '/case/$slug'
    | '/form/$code'
    | '/api/cron/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forms'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/track'
    | '/case/$slug'
    | '/form/$code'
    | '/api/cron/sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forms'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/track'
    | '/case/$slug'
    | '/form/$code'
    | '/api/cron/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FormsRoute: typeof FormsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTrackRoute: typeof ApiTrackRoute
  CaseSlugRoute: typeof CaseSlugRoute
  FormCodeRoute: typeof FormCodeRoute
  ApiCronSyncRoute: typeof ApiCronSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$code': {
      id: '/form/$code'
      path: '/form/$code'
      fullPath: '/form/$code'
      preLoaderRoute: typeof FormCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/$slug': {
      id: '/case/$slug'
      path: '/case/$slug'
      fullPath: '/case/$slug'
      preLoaderRoute: typeof CaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync': {
      id: '/api/cron/sync'
      path: '/api/cron/sync'
      fullPath: '/api/cron/sync'
      preLoaderRoute: typeof ApiCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FormsRoute: FormsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTrackRoute: ApiTrackRoute,
  CaseSlugRoute: CaseSlugRoute,
  FormCodeRoute: FormCodeRoute,
  ApiCronSyncRoute: ApiCronSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
